/* globals.h -- extern declarations for globals.c. */

#ifndef GLOBALS_H
#define GLOBALS_H

#include "types.h"
#include "structs.h"

extern short bjKey;
extern char envOutVol;
extern unsigned short walkAdjust;
extern unsigned short frameCount;
extern short t_sec;
extern short t_min;
extern short t_hour;
extern short t_day;
extern short t_mon;
extern short t_year;
extern PLAYER resident;
extern BOOL16 phoneAnswered;
extern BOOL16 phoneRinging;
extern BOOL16 movingIn;
extern BOOL16 lunchDone;
extern BOOL16 dinnerDone;
extern BOOL16 wakeupDone;
extern BOOL16 bedtimeDone;
extern BOOL16 inEvent;
extern short lastAction;
extern short nextAction;
extern short resX;
extern short resY;
extern BOOL16 loadedSave;
extern long copyProtResult;
extern short walkSpeed;
extern BOOL16 alarmRinging;
extern short waterLevel;
extern short queueCount;
extern short queueActions[];
extern short queuePriority[];
extern short headTarget;
extern short headPose;
extern short headMode;
extern short headFrame;
extern long sfxTicksLeft;
extern BOOL16 noPreempt;
extern BOOL16 patAllowed;
extern short walkXTarget;
extern short walkYTarget;
extern short scratchArr[];
extern BOOL16 frontDoorOpen;
extern BOOL16 studyDoorOpen;
extern BOOL16 bedClosetOpen;
extern BOOL16 kitchenCabOpen;
extern BOOL16 dresserOpen;
extern BOOL16 toiletDoorOpen;
extern BOOL16 filingCabOpen;
extern short bowlLevel;
extern short foodSupply;
extern BOOL16 recordPlaying;
extern BOOL16 tvRunning;
extern short stoveFrames[];
extern char songPlaying;
extern short bowlChange;
extern BOOL16 sfxPlaying;
extern short sfxCurId;
extern BOOL16 organPlaying;
extern char* songBuf;
extern short songCount;
extern short organCount;
extern char *pexName;
extern BOOL16 fireBurning;
extern short fireTimeLeft;
extern BOOL16 fireDouse;
extern BOOL16 keysBlocked;
extern short textTimer;
extern short stripScroll;
extern short typedCursor;
extern char* letterText;
extern char* letterLines[];
extern char* letterSignoffs[];
extern char* monthNames[];
extern short typingSprites[];
extern char letterWord[];
extern char inputLine[];
extern short scnDict[];
extern unsigned char nibbleBytes[];
extern short scnSize;
extern char *scnBuffer;
extern void decodeScn();
extern short* savedBodyImg;
extern short* savedHeadImg;
extern short vdiHandle;
extern short physHandle;
extern short charWidth;
extern short charHeight;
extern short boxWidth;
extern short boxHeight;
extern short colorPens[];
extern short contrl[];
extern short intin[];
extern short ptsin[];
extern short intout[];
extern short ptsout[];
extern void* stripBuf;
extern short mainPalette[];
extern short shirtPrimary[];
extern short shirtSecondary[];
extern short skinColors[];
extern char   fixedChan;
extern char  seqPhase;           /* a byte, not a short */
extern unsigned char* songEvents;
extern unsigned char* songPos;
extern long songAdsr;
extern char  noteVel;            /* a byte, not a short */
extern char defVelocity;
extern char  noteVolume;          /* a byte, not a short */
extern char defPsgVol;
extern short songKey;
extern short ticksPerBeat;
extern short songTempo;
extern short beatTicks;
extern long timerTicks;
extern short seqBusy;
extern short envDivider;
extern short seqCountdown;
extern long  nextEvTick;           /* long tick counters */
extern long  lastExpTick;
extern char  songActive;           /* byte flag */
extern short envBusy;
extern void (*oldTimerAVec)();
extern unsigned char* songEndPtr;
extern unsigned char* loopTarget;
extern char noteDecoded;
extern char noteToQueue;
extern char noteIsOff;
extern char noteChan;
extern char noteNum;
extern char noteMode;
extern char noteAccent;
extern short ticksToNext;
extern short noteDur;
extern char   useSongChan;          /* byte flag */
extern short durTable[];
extern short noteQueue[];
extern short queueLen;
extern long loopStack[];
extern short loopTop;
extern short rampDelta[];
extern short rampAccum[];
extern short envRateTab[];
extern short envTimeTab[];
extern short envRelTab[];
extern short envSusTab[];
extern unsigned char ampRegs[];
extern unsigned char chanMap[];
extern unsigned char noteOwner[];
extern char  sentProgram[];         /* byte array */
extern char *progMap;          /* a byte pointer, not an array */
extern unsigned char defProgMap[];
extern unsigned char noteMap[];
extern unsigned char keyScaleMask[];
extern BOOL16 midiOutOn;
extern unsigned char midiMsg[];
extern long songMaxPos;
extern BOOL16 psgOutOn;
extern char   psgActive;         /* byte flag */
extern unsigned char psgChanNote[];
extern PSG_ENVELOPE psgEnvelope[];
extern char noteHigh;
extern char noteLow;
extern char sfxCurPrio;
extern short sfxDurHi;
extern short sfxDurLo;
extern long sfxStartHz;
extern unsigned char* sfxData[];
extern char sfxBuffer[];
extern void* drawLogbase;
extern void* panelLogbase;
extern void* housePtr;
extern short stripStore[];
extern short screenScale;
extern short work_in[];
extern short wk_out[];
extern short screenMfdb[];   /* a short[10], not an MFDB -- see globals.c */
extern unsigned char altScreen[];
extern unsigned char houseBuf[];
extern short clockMinute;
extern short clockHour;
extern BOOL16 sfxPending;
extern short sfxReqId;
extern short sfxReqDur;
extern short sfxDosStat;
extern short sfxDosCtl;
extern char  sfxPriority[];          /* 26-byte char table */
extern unsigned char objFileBuf[];
extern unsigned char sprFileBuf[];
extern MFDB objMfdbs[];
extern short objWidths[];
extern short objHeights[];
extern short needlePos;
extern short vuLeds;
extern unsigned short vuLedMasks[];
extern short minuteHandXY[];
extern short hourHandXY[];
extern BOOL16 typingOff;
extern char typedLine[];
extern BOOL16 pantryFull;
extern short patFrame;
/* ONE cell shared by two subsystems.  The compositor reads and writes
   it as a word -- renderFrame's frame gate and initSlots's reset -- and the
   sequencer as a byte, and on the 68000 a byte write to a word's
   address lands on its high half.  A union gives each subsystem its
   own access width with no cast.  (`*(char *) &last_hz` does NOT
   work: Alcyon then accesses it as a word, not a byte.) */
union LASTHZ {
        unsigned short  w;      /* renderFrame, initSlots   */
        char            b;      /* parseEvents, queueNote   */
};
extern union LASTHZ lasthz;
#define last_hz  lasthz.w
#define mi_lasT  lasthz.b
extern long lastFrameVbl;
extern void* tosPhysbase;
extern MFDB frameMfdb;
extern MFDB houseMfdb;
extern MFDB* flipMfdb;
extern BOOL16 dogNoTopFlr;
extern short dogIdleCount;
extern BOOL16 dogMayEat;
extern BOOL16 dogEating;
extern short dogEatCount;
extern short dogLastPick;
extern short dogStartPos;
extern short dogYStartNudge;
extern short dogEatFrames[];
extern short dogRoamSpots[];
extern short dogXNudge[];
extern short dogYNudge[];
extern char* parsedLine;
extern short cmdPriority;
extern MFDB slotImgMfdb[];
extern MFDB slotMaskMfdb[];
extern short tvBar0X[];
extern short tvBar0Y[];
extern short tvBar1X[];
extern short tvBar1Y[];
extern short tvBar2X[];
extern short tvBar2Y[];
extern short tvBar3X[];
extern short tvBar3Y[];
extern short tvBarColor[];
extern char phraseBits[];
extern char cmdWord[];
extern short moodPriority[];
extern char bitMask8[];
extern char* anaDict;
extern char* wpzText;
extern short* cardImages;
extern short wpzIndex;
extern short anaNumClues;
extern short anaGuessNum;
extern short anaExtraGuess;
extern BOOL16 anaClueUsed;
extern short anaWordLen;
extern char anaInput[];
extern char* anaAnswer;
extern char anaScrambled[];
extern char* anaWrongMsgs[];
extern char* anaPrompts[];
extern BOOL16 mgTimedOut;
extern short savedTextAttr[];
extern short pkrRound;
extern BOOL16 cardQuit;
extern short compChips;
extern short plyrChips;
extern short potChips;
extern short bjBetMain;
extern short bjBetSplit;
extern BOOL16 bjDidSplit;
extern short warDeck[];
extern short compPile[];
extern short plyrPile[];
extern short plyrWarCards[];
extern short compWarCards[];
extern short warDepth;
extern BOOL16 mouseHidden;
extern short compHand[];
extern short plyrHand[];
extern short compScoring[];
extern short compSorted[];
extern short plyrScoring[];
extern short plyrSorted[];
extern short compRank;
extern short plyrRank;
extern short pkrWinner;
extern short pkrSelected[];
extern short pkrNumDisc;
extern short pkrDiscPile[];
extern short pkrRaiseAmt;
extern short pkrLastBet;
extern short pkrBet;
extern BOOL16 pkrBluffing;
extern BOOL16 pkrPassed;
extern char *pkrMsgBet;
extern char *pkrMsgRaise;
extern char *pkrMsgTake;
extern short bjSplitHand[];
extern short bjHitsMain;
extern short bjHitsDealer;
extern short bjHitsSplit;
extern short bjMatchBet;
extern BOOL16 bjDblMain;
extern BOOL16 bjDblSplit;
extern BOOL16 bjNatMain;
extern BOOL16 bjNatSplit;
extern BOOL16 bjBustMain;
extern BOOL16 bjBustSplit;
extern short bjDealerScore;
extern short bjPlyrScore;
extern char wpzAnswers[][12];
extern short wpzBlanks;
extern char* wpzPrompts[];
extern char* wpzRightMsgs[];
extern char* wpzWrongMsgs[];
extern short cardXComp[];
extern short cardYComp[];
extern short cardXPlyr[];
extern short cardYPlyr[];
extern MFDB cardMfdb[];
extern MFDB cardTableMfdb;
extern BOOL16 isDogDelivery;
extern BOOL16 phoneHangUp;
extern BOOL16 patActive;

#endif /* GLOBALS_H */
