/*
 * alcyon_names.h -- external-symbol aliasing for Alcyon C 4.14.
 *
 * Alcyon truncates external symbols to 7 characters of the C name.
 * The reconstruction uses many long identifiers that would collide
 * at that limit; this header defines short aliases for every one
 * of them.  Included transparently from types.h under __ALCYON__.
 *
 * Also patches Alcyon's missing keywords:
 *   void -> int   (Alcyon has no void; compiler.h uses VOID macro)
 *   enum -> ignore (we use #define anyway, but guard)
 *
 * Generated by tools/gen_alcyon_names.py -- do not edit by hand.
 */

#ifndef ALCYON_NAMES_H
#define ALCYON_NAMES_H

#ifdef __ALCYON__

/* --- Missing Alcyon keywords ------------------------------------- */
#define void  int   /* Alcyon has no void keyword           */

/* --- Function name aliases --------------------------------------- */

/* group [action_] -- 49 items */
#define action_brush_teeth                       a01
#define action_call_dog                          a02
#define action_check_front_door                  a03
#define action_clean_up                          a04
#define action_close_closet_door                 a05
#define action_close_toilet_door                 a06
#define action_dance                             a07
#define action_drink                             a08
#define action_drink_water_animation             a09
#define action_eat_meal                          a10
#define action_feed_dog                          a11
#define action_get_dressed                       a12
#define action_get_in_out_of_bed                 a13
#define action_get_snack_from_fridge             a14
#define action_go_to_bed_night                   a15
#define action_hello                             a16
#define action_kitchen_cabinet                   a17
#define action_light_fireplace                   a18
#define action_listen_song                       a19
#define action_nod_head                          a20
#define action_open_close_bedroom_closet         a21
#define action_open_close_cabinet                a22
#define action_open_close_dresser                a23
#define action_open_close_filing_cabinet         a24
#define action_open_close_fridge                 a25
#define action_open_close_front_door             a26
#define action_open_close_upstairs_closet        a27
#define action_pace_nervously                    a28
#define action_peek_around                       a29
#define action_pet_dog                           a30
#define action_play_a_game                       a31
#define action_play_computer                     a32
#define action_play_piano                        a33
#define action_play_with_record                  a34
#define action_read_newspaper                    a35
#define action_sit_and_exercise                  a36
#define action_sit_on_couch_with_dog             a37
#define action_sleep                             a38
#define action_take_shower                       a39
#define action_tidy_house                        a40
#define action_toggle_tv                         a41
#define action_use_toilet                        a42
#define action_wake_from_alarm                   a43
#define action_wake_up_morning                   a44
#define action_walk_to_and_turn                  a45
#define action_wander_idly                       a46
#define action_wash_hands                        a47
#define action_write_letter                      a48
#define action_yawn_and_stretch                  a49

/* group [asset_l] -- 5 items */
#define asset_load_character_sheets              al01
#define asset_load_lcp                           al02
#define asset_load_names                         al03
#define asset_load_objects_table                 al04
#define asset_load_sprites_table                 al05

/* group [event_r] -- 4 items */
#define event_receive_book_delivery              er01
#define event_receive_dog_food                   er02
#define event_receive_food_delivery              er03
#define event_receive_record_delivery            er04

/* group [file_re] -- 2 items */
#define file_read                                fr01
#define file_read_compressed                     fr02

/* group [lcp_idl] -- 2 items */
#define lcp_idle_look_left                       li01
#define lcp_idle_look_right                      li02

/* group [letter_] -- 3 items */
#define letter_select_typewriter_sound           lt01
#define letter_type_character_animated           lt02
#define letter_type_string_animated              lt03

/* group [midi_he] -- 5 items */
#define midi_header_handle_channel_count         mh01
#define midi_header_handle_program_change        mh02
#define midi_header_handle_scale_table           mh03
#define midi_header_handle_tempo                 mh04
#define midi_header_handle_volume                mh05

/* group [midi_se] -- 10 items */
#define midi_seq_build_scale_table               ms01
#define midi_seq_dispatch_event                  ms02
#define midi_seq_init_song                       ms03
#define midi_seq_parse_channel_map               ms04
#define midi_seq_parse_header                    ms05
#define midi_seq_reset_programs                  ms06
#define midi_seq_send_program_change             ms07
#define midi_seq_set_position                    ms08
#define midi_seq_skip_padding                    ms09
#define midi_seq_start_playback                  ms10

/* group [palette] -- 2 items */
#define palette_apply_clothing_colors            pa01
#define palette_apply_skin_colors                pa02

/* group [screen_] -- 8 items */
#define screen_draw_food_cabinet                 sc01
#define screen_fill_row_black                    sc02
#define screen_fill_row_striped                  sc03
#define screen_fill_row_white                    sc04
#define screen_render_8hz                        sc05
#define screen_scroll_text_down                  sc06
#define screen_set_draw_to_backbuffer            sc07
#define screen_set_draw_to_frontbuffer           sc08

/* group [soundef] -- 4 items */
#define soundeffect_irq_play                     so01
#define soundeffect_select                       so02
#define soundeffects_load                        so03
#define soundeffects_off                         so04

/* group [sprite_] -- 8 items */
#define sprite_draw                              sp01
#define sprite_flip_horizontal                   sp02
#define sprite_init_MFDB                         sp03
#define sprite_lcp_flip                          sp04
#define sprite_lcp_head_animate                  sp05
#define sprite_lcp_head_update                   sp06
#define sprite_update_body                       sp07
#define sprite_update_slots                      sp08

/* group [sprited] -- 4 items */
#define spritedata_select                        sd01
#define spritedata_select_carried_object_left    sd02
#define spritedata_select_carried_object_right   sd03
#define spritedata_update_dog                    sd04

/* group [tv_draw] -- 2 items */
#define tv_draw_static_line                      td01
#define tv_draw_static_noise                     td02

/* group [tv_show] -- 3 items */
#define tv_show_bouncing_line                    th01
#define tv_show_pattern_lines                    th02
#define tv_show_screen_clear                     th03

/* group [tv_turn] -- 2 items */
#define tv_turn_off                              tu01
#define tv_turn_on                               tu02

/* --- Global name aliases ----------------------------------------- */

/* group [_action] -- 4 items */
#define _action_list_size                        ga01
#define _action_priority                         ga02
#define _action_priority_queue                   ga03
#define _action_queue                            ga04

/* group [_hz_200] -- 2 items */
#define _hz_200_hi                               gh01
#define _hz_200_lo                               gh02

/* group [anagram] -- 7 items */
#define anagram_all_clues_used                   gag01
#define anagram_clue_count                       gag02
#define anagram_guess_number                     gag03
#define anagram_input_buffer                     gag04
#define anagram_original_word                    gag05
#define anagram_scrambled_word                   gag06
#define anagram_word_length                      gag07

/* group [clock_h] -- 2 items */
#define clock_hour                               gch01
#define clock_hour_position                      gch02

/* group [clock_m] -- 2 items */
#define clock_minute                             gcm01
#define clock_minute_position                    gcm02

/* group [clothin] -- 2 items */
#define clothing_color_primary                   gcl01
#define clothing_color_secondary                 gcl02

/* group [command] -- 2 items */
#define command_input_buffer                     gcd01
#define command_input_buffer_pos                 gcd02

/* group [dog_des] -- 3 items */
#define dog_dest_x_offset_table                  gdd01
#define dog_dest_y_offset_table                  gdd02
#define dog_destination_position_table           gdd03

/* group [dog_eat] -- 2 items */
#define dog_eating_active                        gde01
#define dog_eating_countdown                     gde02

/* group [dog_fli] -- 2 items */
#define dog_flip_image_buffer                    gdf01
#define dog_flip_mask_buffer                     gdf02

/* group [dog_spr] -- 2 items */
#define dog_sprite_eating_anim_tab               gds01
#define dog_sprite_id                            gds02

/* group [dog_tar] -- 2 items */
#define dog_target_x                             gdt01
#define dog_target_y                             gdt02

/* group [dog_wal] -- 2 items */
#define dog_walk_anim_cycle                      gdw01
#define dog_walk_anim_frames                     gdw02

/* group [dog_way] -- 2 items */
#define dog_waypoint_x                           gdy01
#define dog_waypoint_y                           gdy02

/* group [head_an] -- 5 items */
#define head_anim_current                        gha01
#define head_anim_delay_countdown                gha02
#define head_anim_mode                           gha03
#define head_anim_state_last                     gha04
#define head_anim_target_state                   gha05

/* group [head_sp] -- 4 items */
#define head_sprite_buffer                       ghs01
#define head_sprite_frame                        ghs02
#define head_sprite_mask                         ghs03
#define head_sprite_mirror_flag                  ghs04

/* group [lcp_car] -- 2 items */
#define lcp_carried_object                       glc01
#define lcp_carrying_object_flag                 glc02

/* group [lcp_spr] -- 3 items */
#define lcp_sprite_img                           gls01
#define lcp_sprite_mask                          gls02
#define lcp_sprites_hidden                       gls03

/* group [letter_] -- 4 items */
#define letter_char_width_table                  glt01
#define letter_line_count                        glt02
#define letter_paragraph_count                   glt03
#define letter_scratch_buffer                    glt04

/* group [midi_cu] -- 2 items */
#define midi_current_channel                     gmc01
#define midi_current_program                     gmc02

/* group [midi_no] -- 4 items */
#define midi_note_event_count                    gmn01
#define midi_note_event_index                    gmn02
#define midi_note_hi_limit                       gmn03
#define midi_note_lo_limit                       gmn04

/* group [midi_se] -- 3 items */
#define midi_seq_max_position                    gms01
#define midi_seq_phase                           gms02
#define midi_sequencer_active                    gms03

/* group [midi_so] -- 2 items */
#define midi_song_loop_flag                      gmo01
#define midi_song_max_position                   gmo02

/* group [midi_ti] -- 4 items */
#define midi_tick_counter                        gmt01
#define midi_tick_divider                        gmt02
#define midi_tick_prescaler                      gmt03
#define midi_ticks_per_beat                      gmt04

/* group [object_] -- 33 items */
#define object_id_blue_green                     gob01
#define object_id_cabinet_closed                 gob02
#define object_id_cabinet_open_1                 gob03
#define object_id_cabinet_open_2                 gob04
#define object_id_door_closet_closed             gob05
#define object_id_door_closet_open_1             gob06
#define object_id_door_closet_open_2             gob07
#define object_id_door_front_closed              gob08
#define object_id_door_front_open_1              gob09
#define object_id_door_front_open_2              gob10
#define object_id_door_study_closed              gob11
#define object_id_door_study_open_1              gob12
#define object_id_door_study_open_2              gob13
#define object_id_door_toilet_closed             gob14
#define object_id_door_toilet_open_1             gob15
#define object_id_door_toilet_open_2             gob16
#define object_id_dresser_closed                 gob17
#define object_id_dresser_open_1                 gob18
#define object_id_dresser_open_2                 gob19
#define object_id_filing_cabinet_closed          gob20
#define object_id_filing_cabinet_open_1          gob21
#define object_id_filing_cabinet_open_2          gob22
#define object_id_fireplace_animation            gob23
#define object_id_fireplace_off                  gob24
#define object_id_fridge_closed                  gob25
#define object_id_fridge_open_1                  gob26
#define object_id_fridge_open_2                  gob27
#define object_id_phone_call                     gob28
#define object_id_stove_animation                gob29
#define object_id_stove_off                      gob30
#define object_tab_height                        gob31
#define object_tab_mfdb_table                    gob32
#define object_tab_width                         gob33

/* group [petting] -- 2 items */
#define petting_anim_frame                       gpt01
#define petting_dog_active                       gpt02

/* group [poker_c] -- 3 items */
#define poker_computer_bet                       gpc01
#define poker_computer_draw_pile                 gpc02
#define poker_computer_money                     gpc03

/* group [poker_p] -- 4 items */
#define poker_player_bet                         gpp01
#define poker_player_draw_pile                   gpp02
#define poker_player_money                       gpp03
#define poker_pot_amount                         gpp04

/* group [screen_] -- 2 items */
#define screen_mfdb                              gsr01
#define screen_scroll_down_count                 gsr02

/* group [soundef] -- 13 items */
#define soundeffect_DoSound_Buffer               gso01
#define soundeffect_Hz200                        gso02
#define soundeffect_active_flag                  gso03
#define soundeffect_current                      gso04
#define soundeffect_current_priority             gso05
#define soundeffect_default_duration_hi          gso06
#define soundeffect_default_duration_lo          gso07
#define soundeffect_dosound_control              gso08
#define soundeffect_dosound_status               gso09
#define soundeffect_duration                     gso10
#define soundeffect_playing_flag                 gso11
#define soundeffect_playing_id                   gso12
#define soundeffect_remaining_ticks              gso13

/* group [sprite_] -- 18 items */
#define sprite_active_height                     gse01
#define sprite_active_width                      gse02
#define sprite_active_x                          gse03
#define sprite_active_y                          gse04
#define sprite_def_height                        gse05
#define sprite_def_width                         gse06
#define sprite_layer_flags                       gse07
#define sprite_mfdb_image                        gse08
#define sprite_mfdb_mask                         gse09
#define sprite_pending_flag                      gse10
#define sprite_pending_height                    gse11
#define sprite_pending_width                     gse12
#define sprite_pending_x                         gse13
#define sprite_pending_y                         gse14
#define sprite_slot_map                          gse15
#define sprite_tab_height                        gse16
#define sprite_tab_mfdb_table                    gse17
#define sprite_tab_width                         gse18

/* group [tv_patt] -- 9 items */
#define tv_pattern_0_x_coords                    gtp01
#define tv_pattern_0_y_coords                    gtp02
#define tv_pattern_1_x_coords                    gtp03
#define tv_pattern_1_y_coords                    gtp04
#define tv_pattern_2_x_coords                    gtp05
#define tv_pattern_2_y_coords                    gtp06
#define tv_pattern_3_x_coords                    gtp07
#define tv_pattern_3_y_coords                    gtp08
#define tv_pattern_color_indices                 gtp09

/* group [walk_ta] -- 2 items */
#define walk_target_x                            gwt01
#define walk_target_y                            gwt02

/* group [walk_wa] -- 2 items */
#define walk_waypoint_x                          gww01
#define walk_waypoint_y                          gww02

#endif  /* __ALCYON__ */
#endif  /* ALCYON_NAMES_H */
