/*
 * sprite_compose.c -- host-side smoke test for the sprite compositor.
 *
 * Loads DATA/BODY.LCP into memory, wires body_lcp_file and
 * bodyShapes into it, sets up a minimal PLAYER + world state,
 * and calls updateBody().  Then:
 *   - asserts the compositor wrote non-zero pixels into bodyImage
 *   - asserts drawnX[3] / drawnY[3] track resX/y
 *   - dumps bodyImage to sprite_slot3.pgm as a portable graymap
 *     so the caller can eyeball the shape in any image viewer
 *
 * The .pgm is generated by OR'ing the four bitplanes of each pixel
 * word together to a 1-bit silhouette, then upscaling 1 pixel per
 * output cell.  It's a shape check, not a colour-accurate render --
 * for that you'd need the full VDI blit path plus palette.
 *
 * Build: make sprite_test
 * Run:   from source/build/host/, execute ./sprite_test
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "../include/types.h"
#include "../include/structs.h"
#include "../include/enums.h"
#include "../include/sprites.h"

extern PLAYER   resident;
extern short    resX;
extern short    resY;
extern short    animState;
extern short    resFacing;
extern short    isCarrying;
extern short    debugHideLcp;
extern short    pendReady[];
extern short    drawnX[];
extern short    drawnY[];
/* bodyFrames and bodyShapes are real global ARRAYS in LCP_STX, not
   pointers -- updateBody indexes them with an immediate base and no
   ext.l, which is what pinned the shape (see CLAUDE.md).  So the
   frames are COPIED in here; there is nothing to re-point. */
extern unsigned char    bodyFrames[][168];
extern unsigned char    bodyShapes[][84];
extern short    bodyImage[];
extern short    bodyMask[];
extern short    bodyYOffset[];
extern void     updateBody();
extern void     initMirror();

static int      failures = 0;

#define CHECK(cond, msg) do {                                           \
        if (!(cond)) {                                                  \
                fprintf(stderr, "FAIL %s:%d  %s\n",                     \
                        __FILE__, __LINE__, msg);                       \
                failures++;                                             \
        }                                                               \
} while (0)

/* Dump bodyImage[168 shorts] as a 64x21 1-bit silhouette PGM.
   Each row is 4 words = 64 pixels; the compositor writes one plane
   per pixel-word for now, so any non-zero word => set silhouette. */

static void
dump_pgm(path, buf, rows, words_per_row)
char *          path;
short *         buf;
int             rows;
int             words_per_row;
{
        FILE *  f;
        int     r;
        int     w;
        int     b;
        int     v;

        f = fopen(path, "wb");
        if (f == NULL) { perror(path); return; }
        fprintf(f, "P5\n%d %d\n255\n", words_per_row * 16, rows);
        for (r = 0; r < rows; r++) {
                for (w = 0; w < words_per_row; w++) {
                        v = (unsigned short) buf[r * words_per_row + w];
                        for (b = 15; b >= 0; b--) {
                                unsigned char px;
                                px = (v >> b) & 1 ? 0 : 255;
                                fputc(px, f);
                        }
                }
        }
        fclose(f);
}

int
main(argc, argv)
int     argc;
char ** argv;
{
        FILE *          f;
        unsigned char   header[4];
        long            count;
        long            frame_size;
        long            payload_bytes;
        unsigned char * body_buf;
        unsigned char * shape_buf;
        int             i;
        int             nonzero;
        short           expected_x;
        short           expected_y;

        (void) argc;
        (void) argv;

        /* Load DATA/BODY.LCP.  Header is 2 big-endian shorts
           (count, frame_size), payload follows. */
        f = fopen("../../../DATA/BODY.LCP", "rb");
        if (f == NULL) { perror("open DATA/BODY.LCP"); return 1; }
        if (fread(header, 1, 4, f) != 4) {
                perror("read BODY.LCP header"); return 1;
        }
        count         = ((long) header[0] << 8) | header[1];
        payload_bytes = ((long) header[2] << 8) | header[3];
        frame_size    = payload_bytes / (count ? count : 1);
        printf("BODY.LCP header: count=%ld, payload=%ld bytes, "
               "per-frame=%ld\n", count, payload_bytes, frame_size);
        CHECK(count > 0,             "BODY.LCP count is zero");
        CHECK(payload_bytes > 0,     "BODY.LCP payload is zero");
        CHECK(frame_size == LCP_BODY_FRAME_SIZE,
                                     "BODY.LCP frame_size != LCP_BODY_FRAME_SIZE");
        body_buf = (unsigned char *) malloc(payload_bytes);
        if (body_buf == NULL) { perror("malloc body_buf"); return 1; }
        if ((long) fread(body_buf, 1, payload_bytes, f) != payload_bytes) {
                perror("read BODY.LCP payload"); return 1;
        }
        fclose(f);

        /* Verify the payload has some non-zero pixel data. */
        nonzero = 0;
        for (i = 0; i < payload_bytes; i++)
                if (body_buf[i]) { nonzero = 1; break; }
        CHECK(nonzero, "BODY.LCP payload is all zeros");

        /* Set up a zero mask buffer -- no separate shape file loaded. */
        shape_buf = (unsigned char *) calloc(1, payload_bytes);
        if (shape_buf == NULL) { perror("calloc shape_buf"); return 1; }

        /* Wire globals. */
        memcpy(bodyFrames, body_buf,
               (size_t) ((payload_bytes < 120L * 168L)
                         ? payload_bytes : 120L * 168L));
        memset(bodyShapes, 0, BODY_FRAMES * 84);   /* the whole array */

        /* mirrorTable is BSS in LCP_STX -- initMirror builds the
           bit-reversal LUT at boot (it used to be a shipped
           data table).  Without this the mirrored, right-facing
           frames come out blank. */
        initMirror();
        /* Minimal player + world state, posed in the first walk frame. */
        memset(&resident, 0, sizeof(resident));
        resX                    = 100;
        resY                    = 100;
        animState                = STATE_WALK_FRAME_0;
        resFacing     = FACING_RIGHT;
        isCarrying = 0;
        debugHideLcp = 0;
        pendReady[3]   = 0;

        memset(bodyImage,  0, LCP_BODY_DEST_WORDS * sizeof(short));
        memset(bodyMask, 0, LCP_BODY_DEST_WORDS * sizeof(short));

        /* Call the compositor. */
        updateBody();

        /* The output buffer should now contain the flipped/composited
           frame -- 21 rows × 4 words per row.  Some bit must be set. */
        nonzero = 0;
        for (i = 0; i < LCP_BODY_DEST_WORDS; i++)
                if (bodyImage[i]) { nonzero = 1; break; }
        CHECK(nonzero, "g_lsimg is all zeros after compose");

        /* Position: FACING_RIGHT (=1) picks the "x - 4" branch.
           y = resY + bodyYOffset[0] - 21. */
        expected_x = resX - 4;
        expected_y = resY + bodyYOffset[0] - 21;
        CHECK(drawnX[3] == expected_x,
              "g_seacx[3] mismatch after compose");
        CHECK(drawnY[3] == expected_y,
              "g_seacy[3] mismatch after compose");

        /* Dump the composited slot 3 image for visual inspection. */
        dump_pgm("sprite_slot3.pgm", bodyImage, 21, 4);
        printf("wrote sprite_slot3.pgm (64x21 silhouette)\n");

        free(body_buf);
        free(shape_buf);

        if (failures == 0) {
                printf("sprite_compose: PASS  (compositor produced output)\n");
                return 0;
        }
        printf("sprite_compose: FAIL  (%d assertion(s) failed)\n", failures);
        return 1;
}
