/*
 * t_sprite.c -- host-side smoke test for the sprite compositor.
 *
 * Loads DATA/BODY.LCP into memory, points bodyFrames and
 * bodyShapes at it, sets up a minimal PLAYER + world state,
 * and calls updateBody().  Then:
 *   - asserts the compositor wrote non-zero pixels into bodyImage
 *   - asserts drawnX[3] / drawnY[3] track resX/y
 *   - dumps bodyImage to sprite_slot3.pgm as a portable graymap
 *     so the caller can eyeball the shape in any image viewer
 *
 * The .pgm is generated by OR'ing the four bitplanes of each pixel
 * word together to a 1-bit silhouette, then upscaling 1 pixel per
 * output cell.  It's a shape check, not a colour-accurate render --
 * for that you'd need the full VDI blit path plus palette.
 *
 * Build: make sprite_test
 * Run:   from source/build/host/, execute ./sprite_test
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "../include/types.h"
#include "../include/structs.h"
#include "../include/enums.h"
#include "../include/sprites.h"

extern PLAYER   resident;
extern short    resX;
extern short    resY;
extern short    animState;
extern short    resFacing;
extern short    isCarrying;
extern short    debugHideLcp;
extern short    pendReady[];
extern short    drawnX[];
extern short    drawnY[];
/* bodyFrames and bodyShapes are real global ARRAYS in LCP_STX, not
   pointers -- updateBody indexes them with an immediate base and no
   ext.l, which is what pinned the shape (see docs/history.md).  So the
   frames are COPIED in here; there is nothing to re-point. */
extern unsigned char    bodyFrames[][LCP_BODY_FRAME_SIZE];
extern unsigned char    bodyShapes[][LCP_BODY_SHAPE_SIZE];
extern short    bodyImage[];
extern short    bodyMask[];
extern short    bodyYOffset[];
extern void     updateBody();
extern void     initMirror();

static int      failures = 0;

#define CHECK(cond, msg) do {                                           \
        if (!(cond)) {                                                  \
                fprintf(stderr, "FAIL %s:%d  %s\n",                     \
                        __FILE__, __LINE__, msg);                       \
                failures++;                                             \
        }                                                               \
} while (0)

/* Dump bodyImage[168 shorts] as a 64x21 1-bit silhouette PGM.
   Each row is 4 words = 64 pixels; the compositor writes one plane
   per pixel-word for now, so any non-zero word => set silhouette. */

static void
dump_pgm(path, buf, rows, wordsPerRow)
char *          path;
short *         buf;
int             rows;
int             wordsPerRow;
{
        FILE *  f;
        int     r;
        int     w;
        int     b;
        int     v;

        f = fopen(path, "wb");
        if (f == NULL) { perror(path); return; }
        fprintf(f, "P5\n%d %d\n255\n", wordsPerRow * 16, rows);
        for (r = 0; r < rows; r++) {
                for (w = 0; w < wordsPerRow; w++) {
                        v = (unsigned short) buf[r * wordsPerRow + w];
                        for (b = 15; b >= 0; b--) {
                                unsigned char px;
                                px = (v >> b) & 1 ? 0 : 255;
                                fputc(px, f);
                        }
                }
        }
        fclose(f);
}

int
main(argc, argv)
int     argc;
char ** argv;
{
        FILE *          f;
        unsigned char   header[4];
        long            count;
        long            frameSize;
        long            payloadBytes;
        unsigned char * bodyBuf;
        unsigned char * shapeBuf;
        int             i;
        int             nonzero;
        short           expectedX;
        short           expectedY;

        (void) argc;
        (void) argv;

        /* Load DATA/BODY.LCP.  Header is 2 big-endian shorts
           (count, frameSize), payload follows. */
        f = fopen("../../../DATA/BODY.LCP", "rb");
        if (f == NULL) { perror("open DATA/BODY.LCP"); return 1; }
        if (fread(header, 1, 4, f) != 4) {
                perror("read BODY.LCP header"); return 1;
        }
        count         = ((long) header[0] << 8) | header[1];
        payloadBytes = ((long) header[2] << 8) | header[3];
        frameSize    = payloadBytes / (count ? count : 1);
        printf("BODY.LCP header: count=%ld, payload=%ld bytes, "
               "per-frame=%ld\n", count, payloadBytes, frameSize);
        CHECK(count > 0,             "BODY.LCP count is zero");
        CHECK(payloadBytes > 0,     "BODY.LCP payload is zero");
        CHECK(frameSize == LCP_BODY_FRAME_SIZE,
                                     "BODY.LCP frameSize != LCP_BODY_FRAME_SIZE");
        bodyBuf = (unsigned char *) malloc(payloadBytes);
        if (bodyBuf == NULL) { perror("malloc bodyBuf"); return 1; }
        if ((long) fread(bodyBuf, 1, payloadBytes, f) != payloadBytes) {
                perror("read BODY.LCP payload"); return 1;
        }
        fclose(f);

        /* Verify the payload has some non-zero pixel data. */
        nonzero = 0;
        for (i = 0; i < payloadBytes; i++)
                if (bodyBuf[i]) { nonzero = 1; break; }
        CHECK(nonzero, "BODY.LCP payload is all zeros");

        /* Set up a zero mask buffer -- no separate shape file loaded. */
        shapeBuf = (unsigned char *) calloc(1, payloadBytes);
        if (shapeBuf == NULL) { perror("calloc shapeBuf"); return 1; }

        /* Wire globals. */
        memcpy(bodyFrames, bodyBuf,
               (size_t) ((payloadBytes < 120L * 168L)
                         ? payloadBytes : 120L * 168L));
        memset(bodyShapes, 0, BODY_FRAMES * LCP_BODY_SHAPE_SIZE);   /* the whole array */

        /* mirrorTable is BSS in LCP_STX -- initMirror builds the
           bit-reversal LUT at boot (it used to be a shipped
           data table).  Without this the mirrored, right-facing
           frames come out blank. */
        initMirror();
        /* Minimal player + world state, posed in the first walk frame. */
        memset(&resident, 0, sizeof(resident));
        resX = 100;
        resY = 100;
        animState = STATE_WALK_FRAME_0;
        resFacing = FACING_RIGHT;
        isCarrying = 0;
        debugHideLcp = 0;
        pendReady[3] = 0;

        memset(bodyImage,  0, LCP_BODY_DEST_WORDS * sizeof(short));
        memset(bodyMask, 0, LCP_BODY_DEST_WORDS * sizeof(short));

        /* Call the compositor. */
        updateBody();

        /* The output buffer should now contain the flipped/composited
           frame -- 21 rows × 4 words per row.  Some bit must be set. */
        nonzero = 0;
        for (i = 0; i < LCP_BODY_DEST_WORDS; i++)
                if (bodyImage[i]) { nonzero = 1; break; }
        CHECK(nonzero, "g_lsimg is all zeros after compose");

        /* Position: FACING_RIGHT (=1) picks the "x - 4" branch.
           y = resY + bodyYOffset[0] - 21. */
        expectedX = resX - 4;
        expectedY = resY + bodyYOffset[0] - 21;
        CHECK(drawnX[3] == expectedX, "g_seacx[3] mismatch after compose");
        CHECK(drawnY[3] == expectedY, "g_seacy[3] mismatch after compose");

        /* Dump the composited slot 3 image for visual inspection. */
        dump_pgm("sprite_slot3.pgm", bodyImage, 21, 4);
        printf("wrote sprite_slot3.pgm (64x21 silhouette)\n");

        free(bodyBuf);
        free(shapeBuf);

        if (failures == 0) {
                printf("sprite_compose: PASS  (compositor produced output)\n");
                return 0;
        }
        printf("sprite_compose: FAIL  (%d assertion(s) failed)\n", failures);
        return 1;
}
