/*
 * sprite_compose.c -- host-side smoke test for the sprite compositor.
 *
 * Loads DATA/BODY.LCP into memory, wires body_lcp_file and
 * body_shape_data into it, sets up a minimal PLAYER + world state,
 * and calls sp_updb().  Then:
 *   - asserts the compositor wrote non-zero pixels into g_lsimg
 *   - asserts g_seacx[3] / g_seacy[3] track lcp_x/y
 *   - dumps g_lsimg to sprite_slot3.pgm as a portable graymap
 *     so the caller can eyeball the shape in any image viewer
 *
 * The .pgm is generated by OR'ing the four bitplanes of each pixel
 * word together to a 1-bit silhouette, then upscaling 1 pixel per
 * output cell.  It's a shape check, not a colour-accurate render --
 * for that you'd need the full VDI blit path plus palette.
 *
 * Build: make sprite_test
 * Run:   from csrc/build/host/, execute ./sprite_test
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "../include/types.h"
#include "../include/structs.h"
#include "../include/enums.h"
#include "../include/sprites.h"

extern PLAYER   lcp;
extern short    lcp_x;
extern short    lcp_y;
extern short    lcp_state;
extern short    lcp_facing_direction;
extern short    g_lcyof;
extern short    debug_hide_lcp_offscreen;
extern short    g_sepef[];
extern short    g_seacx[];
extern short    g_seacy[];
extern short *  body_lcp_file;
extern short *  body_shape_data;
extern short    g_lsimg[];
extern short    g_lsmas[];
extern short    body_y_offset_per_state[];
extern void     sp_updb();

static int      failures = 0;

#define CHECK(cond, msg) do {                                           \
        if (!(cond)) {                                                  \
                fprintf(stderr, "FAIL %s:%d  %s\n",                     \
                        __FILE__, __LINE__, msg);                       \
                failures++;                                             \
        }                                                               \
} while (0)

/* Dump g_lsimg[168 shorts] as a 64x21 1-bit silhouette PGM.
   Each row is 4 words = 64 pixels; the compositor writes one plane
   per pixel-word for now, so any non-zero word => set silhouette. */

static void
dump_pgm(path, buf, rows, words_per_row)
char *          path;
short *         buf;
int             rows;
int             words_per_row;
{
        FILE *  f;
        int     r;
        int     w;
        int     b;
        int     v;

        f = fopen(path, "wb");
        if (f == NULL) { perror(path); return; }
        fprintf(f, "P5\n%d %d\n255\n", words_per_row * 16, rows);
        for (r = 0; r < rows; r++) {
                for (w = 0; w < words_per_row; w++) {
                        v = (unsigned short) buf[r * words_per_row + w];
                        for (b = 15; b >= 0; b--) {
                                unsigned char px;
                                px = (v >> b) & 1 ? 0 : 255;
                                fputc(px, f);
                        }
                }
        }
        fclose(f);
}

int
main(argc, argv)
int     argc;
char ** argv;
{
        FILE *          f;
        unsigned char   header[4];
        long            count;
        long            frame_size;
        long            payload_bytes;
        unsigned char * body_buf;
        unsigned char * shape_buf;
        int             i;
        int             nonzero;
        short           expected_x;
        short           expected_y;

        (void) argc;
        (void) argv;

        /* Load DATA/BODY.LCP.  Header is 2 big-endian shorts
           (count, frame_size), payload follows. */
        f = fopen("../../../DATA/BODY.LCP", "rb");
        if (f == NULL) { perror("open DATA/BODY.LCP"); return 1; }
        if (fread(header, 1, 4, f) != 4) {
                perror("read BODY.LCP header"); return 1;
        }
        count         = ((long) header[0] << 8) | header[1];
        payload_bytes = ((long) header[2] << 8) | header[3];
        frame_size    = payload_bytes / (count ? count : 1);
        printf("BODY.LCP header: count=%ld, payload=%ld bytes, "
               "per-frame=%ld\n", count, payload_bytes, frame_size);
        CHECK(count > 0,             "BODY.LCP count is zero");
        CHECK(payload_bytes > 0,     "BODY.LCP payload is zero");
        CHECK(frame_size == LCP_BODY_FRAME_SIZE,
                                     "BODY.LCP frame_size != LCP_BODY_FRAME_SIZE");
        body_buf = (unsigned char *) malloc(payload_bytes);
        if (body_buf == NULL) { perror("malloc body_buf"); return 1; }
        if ((long) fread(body_buf, 1, payload_bytes, f) != payload_bytes) {
                perror("read BODY.LCP payload"); return 1;
        }
        fclose(f);

        /* Verify the payload has some non-zero pixel data. */
        nonzero = 0;
        for (i = 0; i < payload_bytes; i++)
                if (body_buf[i]) { nonzero = 1; break; }
        CHECK(nonzero, "BODY.LCP payload is all zeros");

        /* Set up a zero mask buffer -- no separate shape file loaded. */
        shape_buf = (unsigned char *) calloc(1, payload_bytes);
        if (shape_buf == NULL) { perror("calloc shape_buf"); return 1; }

        /* Wire globals. */
        body_lcp_file   = (short *) body_buf;
        body_shape_data = (short *) shape_buf;

        /* Minimal player + world state.  lcp_state=0 => idle stand pose. */
        memset(&lcp, 0, sizeof(lcp));
        lcp_x                    = 100;
        lcp_y                    = 100;
        lcp_state                = 0;
        lcp_facing_direction     = FACING_RIGHT;
        g_lcyof = 0;
        debug_hide_lcp_offscreen = 0;
        g_sepef[3]   = 0;

        memset(g_lsimg,  0, LCP_BODY_DEST_WORDS * sizeof(short));
        memset(g_lsmas, 0, LCP_BODY_DEST_WORDS * sizeof(short));

        /* Call the compositor. */
        sp_updb();

        /* The output buffer should now contain the flipped/composited
           frame -- 21 rows × 4 words per row.  Some bit must be set. */
        nonzero = 0;
        for (i = 0; i < LCP_BODY_DEST_WORDS; i++)
                if (g_lsimg[i]) { nonzero = 1; break; }
        CHECK(nonzero, "g_lsimg is all zeros after compose");

        /* Position: FACING_RIGHT (=1) picks the "x - 4" branch.
           y = lcp_y + body_y_offset_per_state[0] - 21. */
        expected_x = lcp_x - 4;
        expected_y = lcp_y + body_y_offset_per_state[0] - 21;
        CHECK(g_seacx[3] == expected_x,
              "g_seacx[3] mismatch after compose");
        CHECK(g_seacy[3] == expected_y,
              "g_seacy[3] mismatch after compose");

        /* Dump the composited slot 3 image for visual inspection. */
        dump_pgm("sprite_slot3.pgm", g_lsimg, 21, 4);
        printf("wrote sprite_slot3.pgm (64x21 silhouette)\n");

        free(body_buf);
        free(shape_buf);

        if (failures == 0) {
                printf("sprite_compose: PASS  (compositor produced output)\n");
                return 0;
        }
        printf("sprite_compose: FAIL  (%d assertion(s) failed)\n", failures);
        return 1;
}
